import type { ProtocolFile } from "./protocol";

// 6 activity types shared across all templates — names are consistent so the
// calendar system can reference them reliably.
//
// Names: "Hard ride" | "Easy ride" | "Long ride" | "Race" | "S&C / Gym" | "Run"

export const PROTOCOL_TEMPLATES: ProtocolFile[] = [
  // ─── Endurance Base ─────────────────────────────────────────────────────────
  {
    protocol_name: "Endurance Base",
    description:   "Steady training blocks — balanced fuelling for sustained energy",
    rest_day: {
      calorie_offset:   -400,
      carbs_g_per_kg:   { min: 2,   max: 3   },
      protein_g_per_kg: { min: 1.8, max: 2.0 },
      fat_g_per_kg:     { min: 1.0, max: 1.0 },
    },
    activity_types: [
      {
        name:                   "Hard ride",
        description:            "Intervals, threshold, hill reps",
        calorie_offset:         -100,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 11,
        carbs_g_per_kg:         { min: 7,   max: 9   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.7, max: 0.7 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, moderate protein" },
        during_activity: { carbs_per_hour: 60, description: "60g carbs per hour — gels, bars, or drink mix" },
        post_activity: { timing_minutes_after: 30, focus: "Protein and carbs within recovery window", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.0 },
        default_duration_minutes: 75,
        is_race: false,
      },
      {
        name:                   "Easy ride",
        description:            "Recovery spin, coffee ride, Zone 2",
        calorie_offset:         -300,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 5,
        carbs_g_per_kg:         { min: 3,   max: 4   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.9, max: 0.9 },
        pre_activity:  { timing_hours_before: 2, focus: "Light meal, moderate carbs" },
        during_activity: { carbs_per_hour: 0, description: "Water and electrolytes only" },
        post_activity: { timing_minutes_after: 45, focus: "Light recovery — normal meal timing is fine", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.6 },
        default_duration_minutes: 60,
        is_race: false,
      },
      {
        name:                   "Long ride",
        description:            "Endurance ride, 2.5 hrs+",
        calorie_offset:         -100,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 8,
        carbs_g_per_kg:         { min: 6,   max: 8   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.7, max: 0.7 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, familiar foods" },
        during_activity: { carbs_per_hour: 50, description: "40–60g carbs per hour — mix of drink and solid food" },
        post_activity: { timing_minutes_after: 30, focus: "Protein and carbs within recovery window", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.0 },
        default_duration_minutes: 150,
        is_race: false,
      },
      {
        name:                   "Race",
        description:            "Race day or race-pace effort",
        calorie_offset:         0,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 12,
        carbs_g_per_kg:         { min: 8,   max: 10  },
        protein_g_per_kg:       { min: 1.6, max: 1.6 },
        fat_g_per_kg:           { min: 0.6, max: 0.6 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, low fat — familiar foods only" },
        during_activity: { carbs_per_hour: 80, description: "80–100g carbs per hour — practised race nutrition" },
        post_activity: { timing_minutes_after: 20, focus: "Rapid glycogen replenishment", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.2 },
        default_duration_minutes: 120,
        is_race: true,
      },
      {
        name:                   "S&C / Gym",
        description:            "Strength, weights, core work",
        calorie_offset:         -200,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 6,
        carbs_g_per_kg:         { min: 3,   max: 4   },
        protein_g_per_kg:       { min: 2.0, max: 2.2 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "Balanced meal with protein" },
        during_activity: null,
        post_activity: { timing_minutes_after: 30, focus: "Protein priority for muscle repair", protein_g_per_kg: 0.4, carbs_g_per_kg: 0.5 },
        default_duration_minutes: 45,
        is_race: false,
      },
      {
        name:                   "Run",
        description:            "Running — easy jog to tempo",
        calorie_offset:         -200,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 9,
        carbs_g_per_kg:         { min: 4,   max: 5   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "Light, low fibre, easy to digest" },
        during_activity: { carbs_per_hour: 0, description: "Water only for runs under 60 min" },
        post_activity: { timing_minutes_after: 30, focus: "Recovery meal within 30 minutes", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.8 },
        default_duration_minutes: 40,
        is_race: false,
      },
    ],
    race_week: {
      carb_load_days_before:       3,
      carb_load_g_per_kg:          { min: 8, max: 10 },
      race_morning_carbs_g_per_kg: 2.5,
      race_morning_hours_before:   3,
      strategy_notes: "Taper volume while maintaining intensity, carb load the final 3 days",
    },
  },

  // ─── Race Week ───────────────────────────────────────────────────────────────
  {
    protocol_name: "Race Week",
    description:   "Taper and carb-load for peak race day performance",
    rest_day: {
      calorie_offset:   0,
      carbs_g_per_kg:   { min: 5,   max: 6   },
      protein_g_per_kg: { min: 1.6, max: 1.6 },
      fat_g_per_kg:     { min: 0.8, max: 0.8 },
    },
    activity_types: [
      {
        name:                   "Hard ride",
        description:            "Short sharp session — maintain intensity during taper",
        calorie_offset:         0,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 11,
        carbs_g_per_kg:         { min: 8,   max: 10  },
        protein_g_per_kg:       { min: 1.6, max: 1.8 },
        fat_g_per_kg:           { min: 0.7, max: 0.7 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, familiar foods" },
        during_activity: { carbs_per_hour: 70, description: "70g carbs/hr to stay fuelled during taper sessions" },
        post_activity: { timing_minutes_after: 20, focus: "Fast recovery to top up glycogen", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.2 },
        default_duration_minutes: 75,
        is_race: false,
      },
      {
        name:                   "Easy ride",
        description:            "Taper spin — legs fresh, glycogen topped up",
        calorie_offset:         0,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 5,
        carbs_g_per_kg:         { min: 6,   max: 7   },
        protein_g_per_kg:       { min: 1.6, max: 1.6 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "High carb, low fat, easy to digest" },
        during_activity: { carbs_per_hour: 35, description: "Light fuelling to maintain glycogen stores" },
        post_activity: { timing_minutes_after: 30, focus: "Glycogen replenishment priority", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.0 },
        default_duration_minutes: 60,
        is_race: false,
      },
      {
        name:                   "Long ride",
        description:            "Shortened endurance session — taper week",
        calorie_offset:         0,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 8,
        carbs_g_per_kg:         { min: 8,   max: 10  },
        protein_g_per_kg:       { min: 1.6, max: 1.8 },
        fat_g_per_kg:           { min: 0.6, max: 0.6 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, very familiar foods" },
        during_activity: { carbs_per_hour: 60, description: "60g carbs/hr — practice race nutrition" },
        post_activity: { timing_minutes_after: 20, focus: "Rapid glycogen replenishment", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.2 },
        default_duration_minutes: 90,
        is_race: false,
      },
      {
        name:                   "Race",
        description:            "Race day — peak performance",
        calorie_offset:         0,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 12,
        carbs_g_per_kg:         { min: 8,   max: 10  },
        protein_g_per_kg:       { min: 1.6, max: 1.6 },
        fat_g_per_kg:           { min: 0.6, max: 0.6 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, low fat — familiar foods only" },
        during_activity: { carbs_per_hour: 90, description: "90–100g carbs per hour — peak race nutrition" },
        post_activity: { timing_minutes_after: 20, focus: "Rapid glycogen replenishment", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.2 },
        default_duration_minutes: 120,
        is_race: true,
      },
      {
        name:                   "S&C / Gym",
        description:            "Light activation — no heavy lifting race week",
        calorie_offset:         0,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 6,
        carbs_g_per_kg:         { min: 5,   max: 6   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "Balanced meal, moderate carbs" },
        during_activity: null,
        post_activity: { timing_minutes_after: 30, focus: "Light recovery — carbs priority", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.8 },
        default_duration_minutes: 45,
        is_race: false,
      },
      {
        name:                   "Run",
        description:            "Short shakeout run — taper week",
        calorie_offset:         0,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 9,
        carbs_g_per_kg:         { min: 5,   max: 6   },
        protein_g_per_kg:       { min: 1.6, max: 1.8 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "Light, familiar, easy to digest" },
        during_activity: { carbs_per_hour: 0, description: "Water only — short taper runs" },
        post_activity: { timing_minutes_after: 30, focus: "Carb replenishment", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.8 },
        default_duration_minutes: 30,
        is_race: false,
      },
    ],
    race_week: {
      carb_load_days_before:       3,
      carb_load_g_per_kg:          { min: 10, max: 12 },
      race_morning_carbs_g_per_kg: 3.0,
      race_morning_hours_before:   3,
      strategy_notes: "Days 1–3 taper with moderate carbs, days 4–6 carb load, race morning high carb familiar breakfast",
    },
  },

  // ─── Weight Loss ─────────────────────────────────────────────────────────────
  {
    protocol_name: "Weight Loss",
    description:   "Calorie deficit while protecting training performance",
    rest_day: {
      calorie_offset:   -600,
      carbs_g_per_kg:   { min: 2,   max: 2   },
      protein_g_per_kg: { min: 2.0, max: 2.2 },
      fat_g_per_kg:     { min: 0.8, max: 0.8 },
    },
    activity_types: [
      {
        name:                   "Hard ride",
        description:            "Intervals, threshold, hill reps",
        calorie_offset:         -200,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 11,
        carbs_g_per_kg:         { min: 5,   max: 7   },
        protein_g_per_kg:       { min: 2.0, max: 2.2 },
        fat_g_per_kg:           { min: 0.7, max: 0.7 },
        pre_activity:  { timing_hours_before: 2.5, focus: "Moderate carb, prioritise protein to protect muscle" },
        during_activity: { carbs_per_hour: 50, description: "50g carbs/hr — fuel hard efforts to protect performance" },
        post_activity: { timing_minutes_after: 30, focus: "Protein priority within recovery window", protein_g_per_kg: 0.4, carbs_g_per_kg: 0.8 },
        default_duration_minutes: 75,
        is_race: false,
      },
      {
        name:                   "Easy ride",
        description:            "Recovery spin, Zone 2 fat burning",
        calorie_offset:         -400,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 5,
        carbs_g_per_kg:         { min: 2,   max: 3   },
        protein_g_per_kg:       { min: 2.0, max: 2.2 },
        fat_g_per_kg:           { min: 0.9, max: 0.9 },
        pre_activity:  { timing_hours_before: 2, focus: "Fasted or light — train the fat burn on easy efforts" },
        during_activity: { carbs_per_hour: 0, description: "Water and electrolytes only — maximise fat oxidation" },
        post_activity: { timing_minutes_after: 45, focus: "Light recovery, protein first", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.5 },
        default_duration_minutes: 60,
        is_race: false,
      },
      {
        name:                   "Long ride",
        description:            "Endurance ride, 2 hrs+",
        calorie_offset:         -200,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 8,
        carbs_g_per_kg:         { min: 4,   max: 6   },
        protein_g_per_kg:       { min: 2.0, max: 2.2 },
        fat_g_per_kg:           { min: 0.7, max: 0.7 },
        pre_activity:  { timing_hours_before: 2.5, focus: "Adequate carbs for duration — don't under-fuel long rides" },
        during_activity: { carbs_per_hour: 40, description: "40g carbs/hr — lower than race fuelling, enough to sustain" },
        post_activity: { timing_minutes_after: 30, focus: "Protein and moderate carbs for recovery", protein_g_per_kg: 0.4, carbs_g_per_kg: 0.8 },
        default_duration_minutes: 120,
        is_race: false,
      },
      {
        name:                   "Race",
        description:            "Race day — performance over deficit",
        calorie_offset:         0,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 12,
        carbs_g_per_kg:         { min: 7,   max: 9   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.6, max: 0.6 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, low fat — race day is not a diet day" },
        during_activity: { carbs_per_hour: 70, description: "70–80g carbs/hr on race day — performance first" },
        post_activity: { timing_minutes_after: 20, focus: "Rapid glycogen replenishment", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.0 },
        default_duration_minutes: 120,
        is_race: true,
      },
      {
        name:                   "S&C / Gym",
        description:            "Strength, weights, core work",
        calorie_offset:         -300,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 6,
        carbs_g_per_kg:         { min: 2,   max: 3   },
        protein_g_per_kg:       { min: 2.2, max: 2.4 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "Moderate protein, light carbs" },
        during_activity: null,
        post_activity: { timing_minutes_after: 30, focus: "High protein for muscle repair and body composition", protein_g_per_kg: 0.5, carbs_g_per_kg: 0.4 },
        default_duration_minutes: 45,
        is_race: false,
      },
      {
        name:                   "Run",
        description:            "Running — easy jog to tempo",
        calorie_offset:         -300,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 9,
        carbs_g_per_kg:         { min: 3,   max: 4   },
        protein_g_per_kg:       { min: 2.0, max: 2.2 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "Light, easily digestible, low fat" },
        during_activity: { carbs_per_hour: 0, description: "Water only" },
        post_activity: { timing_minutes_after: 30, focus: "Protein first, moderate carbs", protein_g_per_kg: 0.4, carbs_g_per_kg: 0.6 },
        default_duration_minutes: 40,
        is_race: false,
      },
    ],
    race_week: {
      carb_load_days_before:       2,
      carb_load_g_per_kg:          { min: 8, max: 10 },
      race_morning_carbs_g_per_kg: 2.0,
      race_morning_hours_before:   3,
      strategy_notes: "Ease deficit in the 2 days before race — prioritise performance over loss",
    },
  },

  // ─── General Health ──────────────────────────────────────────────────────────
  {
    protocol_name: "General Health",
    description:   "Balanced nutrition for wellbeing and moderate activity",
    rest_day: {
      calorie_offset:   -200,
      carbs_g_per_kg:   { min: 3,   max: 4   },
      protein_g_per_kg: { min: 1.6, max: 1.8 },
      fat_g_per_kg:     { min: 1.0, max: 1.0 },
    },
    activity_types: [
      {
        name:                   "Hard ride",
        description:            "Intervals, threshold, hill reps",
        calorie_offset:         -100,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 10,
        carbs_g_per_kg:         { min: 5,   max: 7   },
        protein_g_per_kg:       { min: 1.6, max: 1.8 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2.5, focus: "Balanced meal — whole grains, lean protein, moderate fat" },
        during_activity: { carbs_per_hour: 50, description: "50g carbs/hr for harder efforts" },
        post_activity: { timing_minutes_after: 45, focus: "Balanced recovery with whole foods", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.8 },
        default_duration_minutes: 75,
        is_race: false,
      },
      {
        name:                   "Easy ride",
        description:            "Recovery spin, coffee ride, Zone 2",
        calorie_offset:         -200,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 5,
        carbs_g_per_kg:         { min: 3,   max: 4   },
        protein_g_per_kg:       { min: 1.6, max: 1.8 },
        fat_g_per_kg:           { min: 0.9, max: 0.9 },
        pre_activity:  { timing_hours_before: 2, focus: "Light balanced meal — whole foods" },
        during_activity: { carbs_per_hour: 0, description: "Water only — short easy rides don't need fuelling" },
        post_activity: { timing_minutes_after: 45, focus: "Light recovery, normal meal timing is fine", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.6 },
        default_duration_minutes: 60,
        is_race: false,
      },
      {
        name:                   "Long ride",
        description:            "Endurance ride, 2 hrs+",
        calorie_offset:         -100,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 7,
        carbs_g_per_kg:         { min: 5,   max: 7   },
        protein_g_per_kg:       { min: 1.6, max: 1.8 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2.5, focus: "High carb balanced meal — whole grains, fruit, lean protein" },
        during_activity: { carbs_per_hour: 45, description: "40–50g carbs/hr for sustained energy" },
        post_activity: { timing_minutes_after: 30, focus: "Recovery meal with whole foods", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.8 },
        default_duration_minutes: 120,
        is_race: false,
      },
      {
        name:                   "Race",
        description:            "Race day or race-pace effort",
        calorie_offset:         0,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 11,
        carbs_g_per_kg:         { min: 7,   max: 9   },
        protein_g_per_kg:       { min: 1.6, max: 1.6 },
        fat_g_per_kg:           { min: 0.7, max: 0.7 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, familiar foods, low fat and fibre" },
        during_activity: { carbs_per_hour: 70, description: "70–80g carbs/hr" },
        post_activity: { timing_minutes_after: 20, focus: "Balanced rapid recovery", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.0 },
        default_duration_minutes: 90,
        is_race: true,
      },
      {
        name:                   "S&C / Gym",
        description:            "Strength, weights, core work",
        calorie_offset:         -100,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 6,
        carbs_g_per_kg:         { min: 3,   max: 4   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.9, max: 0.9 },
        pre_activity:  { timing_hours_before: 2, focus: "Balanced meal with adequate protein and whole-food carbs" },
        during_activity: null,
        post_activity: { timing_minutes_after: 45, focus: "Balanced recovery meal with whole foods", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.6 },
        default_duration_minutes: 45,
        is_race: false,
      },
      {
        name:                   "Run",
        description:            "Running — easy jog to tempo",
        calorie_offset:         -200,
        add_training_burn:      true,
        burn_rate_kcal_per_min: 9,
        carbs_g_per_kg:         { min: 3,   max: 5   },
        protein_g_per_kg:       { min: 1.6, max: 1.8 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "Light, easily digestible whole foods" },
        during_activity: { carbs_per_hour: 0, description: "Water only" },
        post_activity: { timing_minutes_after: 45, focus: "Balanced recovery meal", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.6 },
        default_duration_minutes: 40,
        is_race: false,
      },
    ],
    race_week: {
      carb_load_days_before:       2,
      carb_load_g_per_kg:          { min: 8, max: 10 },
      race_morning_carbs_g_per_kg: 2.5,
      race_morning_hours_before:   3,
      strategy_notes: "Increase carbs 2 days before, keep breakfast familiar and easily digestible",
    },
  },
];
