import type { ProtocolFile } from "./protocol";

export const PROTOCOL_TEMPLATES: ProtocolFile[] = [
  {
    protocol_name: "Default",
    description:   "Balanced endurance fuelling for cycling training and weight management",
    rest_day: {
      carbs_g_per_kg:   { min: 2,   max: 3   },
      protein_g_per_kg: { min: 1.8, max: 2.0 },
      fat_g_per_kg:     { min: 1.0, max: 1.0 },
    },
    activity_types: [
      {
        name:                   "Hard ride",
        description:            "Intervals, threshold, hill reps",
        burn_rate_kcal_per_min: 11,
        carbs_g_per_kg:         { min: 7,   max: 9   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.7, max: 0.7 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, moderate protein" },
        during_activity: { carbs_per_hour: 60, description: "60g carbs per hour — gels, bars, or drink mix" },
        post_activity: { timing_minutes_after: 30, focus: "Protein and carbs within recovery window", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.0 },
        default_duration_minutes: 75,
        is_race: false,
      },
      {
        name:                   "Easy ride",
        description:            "Recovery spin, coffee ride, Zone 2",
        burn_rate_kcal_per_min: 5,
        carbs_g_per_kg:         { min: 3,   max: 4   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.9, max: 0.9 },
        pre_activity:  { timing_hours_before: 2, focus: "Light meal, moderate carbs" },
        during_activity: { carbs_per_hour: 0, description: "Water and electrolytes only" },
        post_activity: { timing_minutes_after: 45, focus: "Light recovery — normal meal timing is fine", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.6 },
        default_duration_minutes: 60,
        is_race: false,
      },
      {
        name:                   "Long ride",
        description:            "Endurance ride, 2.5 hrs+",
        burn_rate_kcal_per_min: 8,
        carbs_g_per_kg:         { min: 6,   max: 8   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.7, max: 0.7 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, familiar foods" },
        during_activity: { carbs_per_hour: 50, description: "40-60g carbs per hour — mix of drink and solid food" },
        post_activity: { timing_minutes_after: 30, focus: "Protein and carbs within recovery window", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.0 },
        default_duration_minutes: 150,
        is_race: false,
      },
      {
        name:                   "Race",
        description:            "Race day or race-pace effort",
        burn_rate_kcal_per_min: 12,
        carbs_g_per_kg:         { min: 8,   max: 10  },
        protein_g_per_kg:       { min: 1.6, max: 1.6 },
        fat_g_per_kg:           { min: 0.6, max: 0.6 },
        pre_activity:  { timing_hours_before: 3, focus: "High carb, low fibre, low fat — familiar foods only" },
        during_activity: { carbs_per_hour: 80, description: "80-100g carbs per hour — practised race nutrition" },
        post_activity: { timing_minutes_after: 20, focus: "Rapid glycogen replenishment", protein_g_per_kg: 0.3, carbs_g_per_kg: 1.2 },
        default_duration_minutes: 120,
        is_race: true,
      },
      {
        name:                   "S&C / Gym",
        description:            "Strength, weights, core work",
        burn_rate_kcal_per_min: 6,
        carbs_g_per_kg:         { min: 3,   max: 4   },
        protein_g_per_kg:       { min: 2.0, max: 2.2 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "Balanced meal with protein" },
        during_activity: null,
        post_activity: { timing_minutes_after: 30, focus: "Protein priority for muscle repair", protein_g_per_kg: 0.4, carbs_g_per_kg: 0.5 },
        default_duration_minutes: 45,
        is_race: false,
      },
      {
        name:                   "Run",
        description:            "Running — easy jog to tempo",
        burn_rate_kcal_per_min: 9,
        carbs_g_per_kg:         { min: 4,   max: 5   },
        protein_g_per_kg:       { min: 1.8, max: 2.0 },
        fat_g_per_kg:           { min: 0.8, max: 0.8 },
        pre_activity:  { timing_hours_before: 2, focus: "Light, low fibre, easy to digest" },
        during_activity: { carbs_per_hour: 0, description: "Water only for runs under 60 min" },
        post_activity: { timing_minutes_after: 30, focus: "Recovery meal within 30 minutes", protein_g_per_kg: 0.3, carbs_g_per_kg: 0.8 },
        default_duration_minutes: 40,
        is_race: false,
      },
    ],
    race_week: {
      carb_load_days_before:       3,
      carb_load_g_per_kg:          { min: 8, max: 10 },
      race_morning_carbs_g_per_kg: 2.5,
      race_morning_hours_before:   3,
      strategy_notes: "Taper intensity but maintain volume of eating. Practice race-day nutrition in training.",
    },
  },
];
